'use strict';
import * as R from './runtime.js?v=__FW_ASSET_TAG__';
const $=R.$;
let ready=false;
function gFlag(v){return v?'1':'0'}
function fmtTaskPct(n){return typeof n==='number'?n.toFixed(1)+'%':'—'}
function applyTaskProfiler(t){const T=$('hTaskState'),E=$('hTaskElapsed'),B=$('taskTableBody'),H=$('taskTableHint'),A=$('taskProfilerStartButton'),P=$('taskProfilerStopButton'),own=!!R.webUiOwner;if(!t||typeof t.state!='string'){if(T)T.textContent='—';if(E)E.textContent='—';if(B)B.replaceChildren();if(H)H.textContent='';if(A)A.disabled=!own;if(P)P.disabled=true;return}const run=t.state==='running';if(T){let s={never:'Idle',running:'Running',stopped:'Stopped',failed:'Failed'}[t.state]||t.state;if(t.state==='failed'&&t.stopReason&&t.stopReason!=='none')s+=' ('+t.stopReason+')';if(t.state==='stopped'&&t.stopReason==='timeout')s='Stopped (timeout)';T.textContent=s}if(E)E.textContent=run||t.state==='stopped'||t.state==='failed'?Math.floor((t.elapsedMs||0)/1e3)+'s':'—';if(A)A.disabled=run||!own;if(P)P.disabled=!run||!own;if(B){B.replaceChildren();for(const r of t.rows||[]){const tr=document.createElement('tr');[r.name||'—',r.core===0||r.core===1?''+r.core:'—',fmtTaskPct(r.currentCpuPct),fmtTaskPct(r.averageCpuPct),r.stackMinWords!=null?''+r.stackMinWords:'—'].forEach(c=>{const td=document.createElement('td');td.textContent=c;tr.appendChild(td)});B.appendChild(tr)}}if(H){const p=[];if(t.truncated)p.push('List truncated');if(t.unreportedCurrentCpuPct>0.05)p.push('Other now '+t.unreportedCurrentCpuPct.toFixed(1)+'%');if(t.unreportedAverageCpuPct>0.05)p.push('Other avg '+t.unreportedAverageCpuPct.toFixed(1)+'%');if(typeof t.currentTotalCpuPct==='number')p.push('Total now '+t.currentTotalCpuPct.toFixed(1)+'%');H.textContent=p.join(' · ')}}
function applyDiagnosticGuards(s){const g=s&&s.guards;if(!g)return;const live=!!s.machineRunning,b=!!g.bbwEnabled,ns=g.noScale||{},atm=g.atm||{},slow=g.slowExtraction||{},fast=g.fastExtraction||{},touch=g.accidentalTouch||{},cup=g.cupProtection||{},t=(i,v)=>{const e=$(i);if(e)e.textContent=v||'—'};t('dGuardNoScaleUser',R.formatNoScaleGuard(b?{enabled:!!ns.enabled,armed:!!ns.armed}:{enabled:false}));t('dGuardNoScaleRaw','enabled='+gFlag(ns.enabled)+' armed='+gFlag(ns.armed)+' hold='+gFlag(ns.hold)+' scaleWasAvailable='+gFlag(ns.scaleWasAvailable));t('dGuardAtmUser',R.formatAtmGuard({atmEnabled:b&&!!atm.enabled,atmEnforced:live&&!!atm.enforced,atmArmed:live&&!!atm.armed,atmRemainingMs:atm.remainingMs}));t('dGuardAtmRaw','enabled='+gFlag(atm.enabled)+' armed='+gFlag(atm.armed)+' enforced='+gFlag(atm.enforced)+' remainingMs='+(atm.remainingMs||0));t('dGuardSlowUser',R.formatSlowExtractionGuard({guardEnabled:b&&!!slow.enabled,extended:live&&!!slow.extended,goal:slow.activeStopWeightG,inShot:live}));t('dGuardSlowRaw','enabled='+gFlag(slow.enabled)+' extended='+gFlag(slow.extended)+' targetReachedEarly='+gFlag(slow.targetReachedEarly)+' activeStopWeightG='+(typeof slow.activeStopWeightG==='number'?slow.activeStopWeightG.toFixed(1):'0.0'));t('dGuardFastUser',R.formatExtractionGuard({guardEnabled:b&&!!fast.enabled,extended:live&&!!fast.extended,goal:fast.activeStopWeightG,minBbwBrewRemainingMs:fast.minBbwBrewTimeRemainingMs,inShot:live}));t('dGuardFastRaw','enabled='+gFlag(fast.enabled)+' extended='+gFlag(fast.extended)+' targetReachedEarly='+gFlag(fast.targetReachedEarly)+' activeStopWeightG='+(typeof fast.activeStopWeightG==='number'?fast.activeStopWeightG.toFixed(1):'0.0')+' minBbwBrewTimeRemainingMs='+(fast.minBbwBrewTimeRemainingMs||0));t('dGuardTouchUser',R.formatAccidentalTouch({enabled:b&&!!touch.enabled,holding:live&&!!touch.holding,inShot:live}));t('dGuardTouchRaw','enabled='+gFlag(touch.enabled)+' holding='+gFlag(touch.holding)+' phase='+(touch.phase||'STARTUP')+' class='+(touch.class||'OK')+' pendingCount='+(touch.pendingCount||0));t('dGuardCupUser',R.formatCupProtection({enabled:b&&!!cup.enabled,requireCupToStart:!!cup.requireCupToStart,stopIfRemoved:!!cup.stopIfRemoved,present:!!cup.present,scaleUsable:!!g.scaleUsable,inShot:live,aborted:!live&&!!g.lastShotCupRemoved}));t('dGuardCupRaw','enabled='+gFlag(cup.enabled)+' stopIfRemoved='+gFlag(cup.stopIfRemoved)+' requireCupToStart='+gFlag(cup.requireCupToStart)+' present='+gFlag(cup.present)+' startHold='+gFlag(cup.startHold)+' removedPending='+gFlag(cup.removedPending)+' bbwProtectionActive='+gFlag(cup.bbwProtectionActive)+' bbwProtectionEnded='+gFlag(cup.bbwProtectionEnded))}
async function exportDebugData(){const btn=$('exportDebugDataButton');if(btn)btn.disabled=true;R.message('Exporting debug data…');try{const data=await R.api('/api/v1/debug/export',{timeoutMs:3e4});if(!data||typeof data.exportSchemaVersion!=='number')throw new Error('Invalid debug export');const a=document.createElement('a'),boot=typeof data.bootId==='number'?data.bootId:R.bootId||0;a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='shotstopper-debug-boot'+boot+'-'+new Date().toISOString().replace(/[:.]/g,'-').slice(0,19)+'.json';document.body.appendChild(a);a.click();a.remove();R.message('Debug data exported.','ok');R.noteReachOk()}catch(e){R.message(R.formatCommandError('Could not export debug data.',e),'error');R.noteReachFail(e)}finally{if(btn)btn.disabled=false}}
export function applyStatus(s){R.applyDiagnosticStatus(s);if(s&&s.adminUnlocked){applyDiagnosticGuards(s);applyTaskProfiler(s.tasks)}}
export function init(){
  if(ready)return;
  ready=true;
  R.registerViewStatus('diagnostic',applyStatus);
  const unlock=()=>{const pw=$('diagnosticUnlockPassword').value;if(!pw){R.showFieldError('diagnosticUnlockPassword','Device password is required.');return}R.clearFieldErrors();R.api('/api/v1/admin/unlock',{method:'POST',body:R.body({password:pw})}).then(()=>{$('diagnosticUnlockPassword').value='';R.noteReachOk();R.message('Diagnostics unlocked.','ok');return R.refreshStatus()}).catch(e=>R.message(R.formatCommandError('Could not unlock diagnostics.',e),'error'))};
  $('diagnosticUnlockButton').onclick=unlock;
  $('diagnosticUnlockPassword').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();unlock()}});
  $('diagnosticLockButton').onclick=R.lockAdmin;
  if($('serialDebugOutput'))$('serialDebugOutput').onchange=()=>R.command('/api/v1/config',R.withBaseRev({serialDebugOutput:!!$('serialDebugOutput').checked}));  if($('ringRetainLogLevel'))$('ringRetainLogLevel').onchange=()=>R.command('/api/v1/config',R.withBaseRev({ringRetainLogLevel:$('ringRetainLogLevel').value||'none'}));
  $('logFilter').onchange=R.renderLog;
  $('logLevelFilter').onchange=R.renderLog;
  $('copyLogButton').onclick=()=>navigator.clipboard&&navigator.clipboard.writeText($('log').value);
  $('clearLogButton').onclick=()=>R.clearLogView();
  if($('exportDebugDataButton'))$('exportDebugDataButton').onclick=()=>exportDebugData();
  $('taskProfilerStartButton').onclick=()=>R.command('/api/v1/diagnostic/profiler',{enabled:true});
  $('taskProfilerStopButton').onclick=()=>R.command('/api/v1/diagnostic/profiler',{enabled:false});
}
export function activate(){}
