#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const repoRoot = path.resolve(__dirname, '..');
const sourcePath = path.join(repoRoot, 'shotStopper', 'ShotStopperWebAssets.h');
const outputPath =
    path.join(repoRoot, 'shotStopper', 'ShotStopperWebAssetsGzip.h');

function extractHtml(source) {
  const match = source.match(/R"HTML\(([\s\S]*?)\)HTML"/);
  if (!match) {
    throw new Error('Embedded HTML raw string not found');
  }
  return match[1];
}

function collapseMarkup(markup) {
  return markup.replace(/>\s+</g, '><');
}

function minifyHtml(html) {
  html = html.replace(/<!--[\s\S]*?-->/g, '');
  const pieces = [];
  const re =
      /(<script\b[^>]*>)([\s\S]*?)(<\/script>)|(<style\b[^>]*>)([\s\S]*?)(<\/style>)/gi;
  let last = 0;
  let match;
  while ((match = re.exec(html))) {
    pieces.push(collapseMarkup(html.slice(last, match.index)));
    if (match[1]) {
      pieces.push(match[1], match[2], match[3]);
    } else {
      pieces.push(match[4], match[5], match[6]);
    }
    last = match.index + match[0].length;
  }
  pieces.push(collapseMarkup(html.slice(last)));
  return pieces.join('').trim();
}

function formatByteArray(buffer) {
  const lines = [];
  for (let offset = 0; offset < buffer.length; offset += 12) {
    const slice = buffer.subarray(offset, offset + 12);
    const body = Array.from(slice, (byte) =>
      `0x${byte.toString(16).padStart(2, '0')}`
    ).join(', ');
    const suffix = offset + 12 < buffer.length ? ',' : '';
    lines.push(`    ${body}${suffix}`);
  }
  return lines.join('\n');
}

function generate() {
  const source = fs.readFileSync(sourcePath, 'utf8');
  const html = minifyHtml(extractHtml(source));
  const gzip = zlib.gzipSync(Buffer.from(html, 'utf8'), {level: 9});
  const header =
      `#pragma once

#include <pgmspace.h>
#include <stddef.h>
#include <stdint.h>

namespace shotstopper {

// Generated by scripts/gen_web_ui.js — do not edit.

constexpr size_t SHOT_STOPPER_WEB_UI_GZIP_LEN = ${gzip.length};
const uint8_t SHOT_STOPPER_WEB_UI_GZIP[] PROGMEM = {
${formatByteArray(gzip)}
};

static_assert(sizeof(SHOT_STOPPER_WEB_UI_GZIP) == SHOT_STOPPER_WEB_UI_GZIP_LEN,
              "gzip Web UI length mismatch");

}  // namespace shotstopper
`;
  fs.writeFileSync(outputPath, header);
  return {html, gzip, outputPath, sourcePath};
}

module.exports = {extractHtml, minifyHtml, generate, sourcePath, outputPath};

if (require.main === module) {
  const result = generate();
  const htmlBytes = Buffer.byteLength(result.html, 'utf8');
  console.log(
      `Generated ${result.outputPath} (${result.gzip.length} bytes gzip, ${htmlBytes} bytes HTML)`
  );
}
