#!/bin/sh
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
version_file="$root/VERSION"
output="$root/shotStopper/ShotStopperVersion.h"

ver=$(tr -d '[:space:]' < "$version_file")
case "$ver" in
  *[!0-9.]*|""|*.*.*.*)
    echo "Invalid VERSION: '$ver' (expected MAJOR.MINOR.PATCH)" >&2
    exit 1
    ;;
esac

major=${ver%%.*}
rest=${ver#*.}
minor=${rest%%.*}
patch=${rest#*.}

if [ -z "$major" ] || [ -z "$minor" ] || [ -z "$patch" ]; then
  echo "Invalid VERSION: '$ver' (expected MAJOR.MINOR.PATCH)" >&2
  exit 1
fi

packed=$(( (major << 24) | (minor << 16) | patch ))

if git -C "$root" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  sha=$(git -C "$root" rev-parse --short=7 HEAD)
  dirty=""
  if ! git -C "$root" diff --quiet || ! git -C "$root" diff --cached --quiet; then
    dirty="-dirty"
  fi
else
  sha="unknown"
  dirty=""
fi

build_id="${ver}+${sha}${dirty}"

cat > "$output" <<EOF
#pragma once

// Generated by scripts/gen_version.sh — do not edit.

namespace shotstopper {

constexpr char FW_VERSION[] = "${build_id}";
constexpr uint32_t FW_VERSION_PACKED = 0x$(printf '%08x' "$packed")U;

}  // namespace shotstopper
EOF

echo "Generated $output ($build_id)"
