#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const repoRoot = path.resolve(__dirname, '..');
const sourcePath = path.join(repoRoot, 'shotStopper', 'ShotStopperWebAssets.h');
const cssSourcePath = path.join(repoRoot, 'shotStopper', 'web', 'app.css');
const logoSourcePath = path.join(repoRoot, 'shotStopper', 'web', 'logo.svg');
const versionPath = path.join(repoRoot, 'shotStopper', 'ShotStopperVersion.h');
const outputPath =
    path.join(repoRoot, 'shotStopper', 'ShotStopperWebAssetsGzip.h');

function extractHtml(source) {
  const match = source.match(/R"HTML\(([\s\S]*?)\)HTML"/);
  if (!match) {
    throw new Error('Embedded HTML raw string not found');
  }
  return match[1];
}

function readFirmwareVersion() {
  if (!fs.existsSync(versionPath)) {
    return 'dev';
  }
  const source = fs.readFileSync(versionPath, 'utf8');
  const match = source.match(/FW_VERSION\[\]\s*=\s*"([^"]+)"/);
  return match ? match[1] : 'dev';
}

function collapseMarkup(markup) {
  return markup.replace(/>\s+</g, '><');
}

function minifyHtml(html) {
  html = html.replace(/<!--[\s\S]*?-->/g, '');
  const pieces = [];
  const re =
      /(<script\b[^>]*>)([\s\S]*?)(<\/script>)|(<style\b[^>]*>)([\s\S]*?)(<\/style>)/gi;
  let last = 0;
  let match;
  while ((match = re.exec(html))) {
    pieces.push(collapseMarkup(html.slice(last, match.index)));
    if (match[1]) {
      pieces.push(match[1], match[2], match[3]);
    } else {
      pieces.push(match[4], match[5], match[6]);
    }
    last = match.index + match[0].length;
  }
  pieces.push(collapseMarkup(html.slice(last)));
  return pieces.join('').trim();
}

function minifyCss(css) {
  return css
      .replace(/\/\*[\s\S]*?\*\//g, '')
      .replace(/\s+/g, ' ')
      .replace(/\s*([{}:;,])\s*/g, '$1')
      .replace(/;}/g, '}')
      .trim();
}

function minifySvg(svg) {
  return svg
      .replace(/<\?xml[^?]*\?>/gi, '')
      .replace(/<!DOCTYPE[^>]*>/gi, '')
      .replace(/<!--[\s\S]*?-->/g, '')
      .replace(/\s+/g, ' ')
      .replace(/> </g, '><')
      .trim();
}

function formatByteArray(buffer) {
  const lines = [];
  for (let offset = 0; offset < buffer.length; offset += 12) {
    const slice = buffer.subarray(offset, offset + 12);
    const body = Array.from(slice, (byte) =>
      `0x${byte.toString(16).padStart(2, '0')}`
    ).join(', ');
    const suffix = offset + 12 < buffer.length ? ',' : '';
    lines.push(`    ${body}${suffix}`);
  }
  return lines.join('\n');
}

function generate() {
  const source = fs.readFileSync(sourcePath, 'utf8');
  const cssSource = fs.readFileSync(cssSourcePath, 'utf8');
  const logoSource = fs.readFileSync(logoSourcePath, 'utf8');
  const version = readFirmwareVersion();
  const html = minifyHtml(
      extractHtml(source).split('__FW_VERSION__').join(version));
  const css = minifyCss(cssSource);
  const logo = minifySvg(logoSource);
  const htmlGzip = zlib.gzipSync(Buffer.from(html, 'utf8'), {level: 9});
  const cssGzip = zlib.gzipSync(Buffer.from(css, 'utf8'), {level: 9});
  const logoGzip = zlib.gzipSync(Buffer.from(logo, 'utf8'), {level: 9});
  const header =
      `#pragma once

#include <pgmspace.h>
#include <stddef.h>
#include <stdint.h>

namespace shotstopper {

// Generated by scripts/gen_web_ui.js — do not edit.

constexpr size_t SHOT_STOPPER_WEB_UI_GZIP_LEN = ${htmlGzip.length};
const uint8_t SHOT_STOPPER_WEB_UI_GZIP[] PROGMEM = {
${formatByteArray(htmlGzip)}
};

static_assert(sizeof(SHOT_STOPPER_WEB_UI_GZIP) == SHOT_STOPPER_WEB_UI_GZIP_LEN,
              "gzip Web UI length mismatch");

constexpr size_t SHOT_STOPPER_WEB_CSS_GZIP_LEN = ${cssGzip.length};
const uint8_t SHOT_STOPPER_WEB_CSS_GZIP[] PROGMEM = {
${formatByteArray(cssGzip)}
};

static_assert(sizeof(SHOT_STOPPER_WEB_CSS_GZIP) == SHOT_STOPPER_WEB_CSS_GZIP_LEN,
              "gzip Web CSS length mismatch");

constexpr size_t SHOT_STOPPER_WEB_LOGO_GZIP_LEN = ${logoGzip.length};
const uint8_t SHOT_STOPPER_WEB_LOGO_GZIP[] PROGMEM = {
${formatByteArray(logoGzip)}
};

static_assert(sizeof(SHOT_STOPPER_WEB_LOGO_GZIP) == SHOT_STOPPER_WEB_LOGO_GZIP_LEN,
              "gzip Web logo length mismatch");

}  // namespace shotstopper
`;
  fs.writeFileSync(outputPath, header);
  return {
    html,
    css,
    logo,
    gzip: htmlGzip,
    cssGzip,
    logoGzip,
    outputPath,
    sourcePath,
    cssSourcePath,
    logoSourcePath,
    version,
  };
}

module.exports = {
  extractHtml,
  minifyHtml,
  minifyCss,
  minifySvg,
  generate,
  sourcePath,
  cssSourcePath,
  logoSourcePath,
  outputPath,
};

if (require.main === module) {
  const result = generate();
  const htmlBytes = Buffer.byteLength(result.html, 'utf8');
  const cssBytes = Buffer.byteLength(result.css, 'utf8');
  const logoBytes = Buffer.byteLength(result.logo, 'utf8');
  console.log(
      `Generated ${result.outputPath} ` +
          `(HTML ${result.gzip.length} B gzip / ${htmlBytes} B, ` +
          `CSS ${result.cssGzip.length} B gzip / ${cssBytes} B, ` +
          `logo ${result.logoGzip.length} B gzip / ${logoBytes} B, ` +
          `v=${result.version})`
  );
}
