name=EspressoScaleBLE
version=4.1.0
author=Felipe Urzúa <cheerpipe@gmail.com>
maintainer=Felipe Urzúa <cheerpipe@gmail.com>
sentence=A library that connects BLE devices to Acaia, Bookoo, Felicita, Eclair, Decent, DiFluid, MyScale, Varia, Eureka, and WeighMyBru scales.
paragraph=Uses the ArduinoBLE library and should support any BLE module.
category=Device Control
url=https://github.com/Cheerpipe/AcaiaArduinoBLE
architectures=esp32,samd
includes=EspressoScaleBLE.h
depends=ArduinoBLE (=2.1.0)
